ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter netdev_default,$(USEMODULE)))
  LORA_DRIVER ?= sx1272
  LORA_REGION ?= EU868
  USEMODULE += $(LORA_DRIVER)
endif

# Accelerometer, altimeter and mems to add

# eeprom : STM32L151CC EEPROM_SIZE is not defined into cpu/stm32/include/periph/l1/periph_cpu.h
CFLAGS +=-DEEPROM_SIZE=8096U
